name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PROJECT_TYPE: KEXT
  SCHEME: LegacyRed

jobs:
  build:
    runs-on: macos-latest
    steps:
      # 1️⃣ Checkout the repo with submodules
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2️⃣ Bootstrap Lilu
      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1

      # 3️⃣ Build Debug
      - name: Build Debug
        run: xcodebuild -scheme $SCHEME -configuration Debug

      # 4️⃣ Build Release
      - name: Build Release
        run: xcodebuild -scheme $SCHEME -configuration Release

      # 5️⃣ Upload the KEXT directly (no ZIP)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LegacyRed-Kexts
          path: "$(xcodebuild -scheme $SCHEME -configuration Release -showBuildSettings | grep -m1 -A1 BUILT_PRODUCTS_DIR | tail -n1 | xargs)/$SCHEME.kext"
