name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PROJECT_TYPE: KEXT
  SCHEME: LegacyRed

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1

      - name: Lilu Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/Lilu/master/Lilu/Scripts/bootstrap.sh) && eval "$src" || exit 1

      - name: Build Debug
        run: xcodebuild -scheme $SCHEME -configuration Debug

      - name: Build Release
        run: xcodebuild -scheme $SCHEME -configuration Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LegacyRed-Kexts
          path: build/*/*.zip
